### ISSUE TITLE
Any Resume or Selective Starting Functionality?

### ISSUE THREAD

**Issue by micahasmith** [famzah/encrypted-s3-backup#1]
After a while i keep getting:

```
/root/bin/encrypted-s3-sync: line 17: 18297 Terminated              aws --profile "$AWS_PROFILE" --output text "$@" --region "$AWS_REGION" --cli-read-timeout "$AWS_NET_TIMEOUT" --cli-connect-timeout "$AWS_NET_TIMEOUT"
```

And then the job fails. Any way to resume or pick a location for it to start at?

Thx!

**Comment by famzah** [comment]
Hi Micah,

Sorry for the late reply. I was on a holiday with limited Internet access.

The unexpected "Terminated" error suggests that this process was probably killed (by the Linux kernel or some other program). Such forcible termination of a process is usually caused because some resource or security limits were hit. The most common case for resource limits is the maximum memory limit (ulimit -v), the CPU time limit (ulimit -t), or the maximum opened files limit (ulimit -n). You can see all your limits by executing "ulimit -a".

I guess you are running with "root" since the file is located in "/root/bin/encrypted-s3-sync" which suggests that resource limits shouldn't be a problem though...

The best I can suggest is that you edit "/root/bin/encrypted-s3-sync" and put "set -x" after the existing "set -u" line at the beginning of the script. This will run the Bash script in debug/trace mode.

Additionally, you should also check and eventually provide the log entries that the script produced. It logs in Syslog by using the "user.info" and "user.crit" priorities. The syslog messages are prefixed with "encrypted-s3-sync", so you can easily "grep" for them in "/var/log", in order to see in which file they are written.

You can also see if "dmesg" outputs something related to the process termination.

---

Regarding the resume action. This is not possible. The entire backup process relies on the "aws s3 sync" CLI command, and it does not support resume. Each backup specified by a "config_file" is always started from the scratch by "encrypted-s3-sync".

You can split your data directories into several "encrypted-s3-sync" config files. This way you won't have to start the backup of your whole directory tree every time from scratch. I have 15 config files for my PC, for example. That's mostly because I don't want to backup the whole Windows "C:\", which I have exported under my Linux VM.

**Comment by micahasmith** [comment]
Thank you so much for the library and your reply/time! Great response.
